### PR TITLE
Creating david.txt

### PR DESCRIPTION
**Pull request by daboross**
Hi,

I'm not 100% sure about all the steps in the list in README.md, but I've completed at least a few of them.

I couldn't find any `master.txt` file, and I'm really not sure what would cause merge conflicts with adding files, but here's a PR, at least?

### CODE REVIEW

**Comment by guptad2** [comment]
Hi sorry about that david, there now exists a master.txt

**Comment by daboross** [comment]
Thanks!

**Comment by guptad2** [comment]
Oops so sorry about that, you don't need to make any changes to it (if you have it is totally ok). I guess I cause a little confusion :(

**Comment by daboross** [comment]
It's all good! Thanks.

**Pull request closed without merging**
